### ISSUE TITLE
performance test (pixel drawing on google maps)

### ISSUE THREAD

**Issue by inyukwo1** [moon920110/canvearth#16]
need to measure exact elapsed time for drawing

**Comment by prodia4** [comment]
Case 1: When VIEW_GRID_ZOOM_DIFF = 3, showing about 400 pixels on the screen, drawing takes about 3~400 mil seconds. 

Case 2: When it is 4, showing about 1200 pixels on the screen, drawing takes about 1 second and skips some frames. (I/Choreographer: Skipped 57 frames!  The application may be doing too much work on its main thread.)

Adding the pixel instances itself(without drawing the polygons) has no overhead, taking about 1~10 ms in both case 1 & 2.

**Comment by inyukwo1** [comment]
Thanks. Maybe we will need profiling if performance issue matterss

**Comment by inyukwo1** [comment]
Thanks. Maybe we will need profiling if performance issue matterss
