### ISSUE TITLE
Need confirmation of server-side api

### ISSUE THREAD

**Issue by inyukwo1** [moon920110/canvearth#27]
Can be seen at FBPixelManager class.

**Comment by inyukwo1** [comment]
I confirmed, please close this issue @mrgomdev @YoungsooJang

**Comment by prodia4** [comment]
1. I Need to know the firebaseId of the watching pixel when watchingPixelChanged is called, but currently fbPixel, which is passed to PixelEvents.watchingPixelChanged, does not contain firebaseId. How about including id(firebaseId) as a member variable in FBPixel?

2. What is the use case of readPixelInstantly?

Other than that, the api seems good to me for now.

**Comment by inyukwo1** [comment]
1. I will add PixelData parameter at the event function. I don't want to add PixelData at the FBPixel. I will make a pull request soon.
2. updateParent and unit tests.

**Comment by inyukwo1** [comment]
@YoungsooJang @mrgomdev Okay for you? I will close this issue at tomorrow.
